// <auto-generated />
using System;
using GenDataBase;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GenDataBase.Migrations
{
    [DbContext(typeof(GenDbContext))]
    [Migration("20240122091944_first")]
    partial class first
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Entities.ApplicationUser.PrimaryUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("First_Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Last_Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Remain_SignedIn")
                        .HasColumnType("bit");

                    b.Property<int>("roles")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Primary Users", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("f65dee5c-a3bb-4b8e-a12c-78b6e3e7e517"),
                            Email = "ben10@gmail.com",
                            First_Name = "Ben",
                            Last_Name = "Tennyson",
                            PasswordHash = "Paashw",
                            Remain_SignedIn = true,
                            roles = 0
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
